---
- name: Get active interfaces
  shell: ip route get 8.8.8.8 | awk 'NR==1 {print $5}'
  register: active_interface

- name: Find yml file where interface is located
  shell: grep -rw -m 1 "{{ active_interface.stdout }}" /etc/netplan/ | awk -F':' '{print $1}'
  register: found_file


- name: Change /etc/netplan file
  template:
    src: interface-cfg.j2
    dest: "{{ found_file.stdout }}"
  notify: Change interface

