---
- include_tasks: crypt_disk.yml
- include_tasks: interface.yml

- name: Disable C-states for all CPUs
  command: echo 1 > /sys/devices/system/cpu/cpu*/cpuidle/state*/disable
  register: c_state_result

- name: Print message if file was not modified
  debug:
    msg: "C-State was not modified"
  when: c_state_result.rc != 0

- name: Check if line exists in file
  shell: grep -q "intel_pstate=performance" /etc/default/grub
  register: grep_result
  changed_when: false
  no_log: true
  ignore_errors: true

- name: Open file GRUB loader
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="(.*)"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 intel_pstate=performance"'
    backrefs: yes
  when: grep_result.rc != 0
  notify:
    - Updating GRUB loader

- name: Get processor list
  shell: lscpu | grep "Model name" | awk -F':' '{print $2}'
  register: cpu_list

- name: Get Hyper-Threading information
  shell: lscpu | grep "Thread(s) per core" | awk -F':' '{print $2}'
  register: hyper_threading_info

- name: truncate spaces
  set_fact:
    hyper_threading_info: "{{ hyper_threading_info.stdout | regex_replace('\\s', '') }}"
    cpu_list: "{{ cpu_list.stdout_lines | map('regex_replace', '\\s', '') | list }}"

- name: Print list of processors
  debug:
    var: cpu_list

- name: Print Hyper-Threading information
  debug:
    var: hyper_threading_info

