- name: Interface information output
  command: ip addr show net0

- name: Updating GRUB loader
  command: update-grub

- name: Change interface
  command: netplan try

- name: Save fstab
  command: "mount -a"
